name: Potpourri CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  SSL_CERT_DIR: /etc/ssl/certs
  NODE_TLS_REJECT_UNAUTHORIZED: 0

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    environment:
      name: test_environment
      url: ${{ steps.step_name.outputs.url_output }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install NPM packages
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./build

  deploy:
    permissions: write-all
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build